# Site settings
title: lucasm4c | hacker, ativista e pai
description: lucasm4c website
url: "https://lucasm4c.github.io/"

# User settings
username: lucasm4c
user_title: hacker, ativista e pai.
twitter_username: _lucasm4c
github_username: lucasm4c
email: lucasmac@protonmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Tags
    url: /tags
  
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
